SWIFT_CXX_HEADER := swift-class.h
SWIFT_SOURCES := swift-class.swift
CXX_SOURCES := main.cpp
SWIFT_CXX_INTEROP := 1
SWIFTFLAGS_EXTRAS = -Xcc -I$(SRCDIR) -parse-as-library -g
CFLAGS = -I. -g
include Makefile.rules
